### ISSUE TITLE
how to backup and restore? commands not clear

### ISSUE THREAD

**Issue by LDubya** [arkadiusjonczek/imapdump#1]
Hi there, @arkadiusjonczek  thanks for making this! ^_^ 

This could be an issue with me misunderstanding the docs, but basically I'm not seeing how to:

- backup an inbox
- restore the inbox

Can you give instructions how?

The "dump" command claims to "Backup and restore your imap mailboxes.": 

> $php imap
> Console Tool
> 
> Usage:
>   command [options] [arguments]
> 
> Options:
>   -h, --help            Display this help message
>   -q, --quiet           Do not output any message
>   -V, --version         Display this application version
>       --ansi            Force ANSI output
>       --no-ansi         Disable ANSI output
>   -n, --no-interaction  Do not ask any interactive question
>   -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
> 
> Available commands:
>   **dump  Backup and restore your imap mailboxes.**
>   help  Displays help for a command
>   info  Information about your imap mailbox.
>   list  Lists commands
>   ls    List your imap mailboxes.

But it doesn't seem to take any arguments / parameters:

> $php imap dump -h
> Usage:
>   dump
> 
> Options:
>   -h, --help            Display this help message
>   -q, --quiet           Do not output any message
>   -V, --version         Display this application version
>       --ansi            Force ANSI output
>       --no-ansi         Disable ANSI output
>   -n, --no-interaction  Do not ask any interactive question
>   -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

**Comment by arkadiusjonczek** [comment]
Hi @LDubya my friend,

the backup and restore function isn't implemented yet. Sorry for that.

Can you give me more details about your requirements for this functionality? So I can try to implement it asap.

**Comment by LDubya** [comment]
oh wow thanks for the quick response @arkadiusjonczek !

The goal is to use a command-line tool like this to back up (and restore when necessary) email mailboxes onto local storage. Let's say I have 10 different email addresses that I can connect to over IMAP. I'd like to back up their contents locally... say once a day/week/month.

Then being able to restore a mailbox to a specific snapshot.

**Comment by arkadiusjonczek** [comment]
Hey @LDubya, hope you are good.

I just added the first backup and restore feature. 🎉 

For now it just support full backup and restore. But it seems to work very good. I tested it with my mail account.

Please give me feedback if it works for you. I also need some details about your directory structure in your mail account because mine is very simple (only subdirectories inside of inbox).
